service: test-sls

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  lambdaHashingVersion: 20201221

custom:
  pythonRequirements:
    usePipenv: true
  defaultStage: dev
  defaultRegion: ap-northeast-1
  #environment:
    #dev:
    #prod:

functions:
  hello:
    handler: handler.hello
    #environment: ${self:custom.environment.${self:provider.stage}}

stepFunctions: ${file(includes/state-machines.yml)}

plugins:
  - serverless-step-functions
  - serverless-python-requirements
