service: check-sfn-context-object

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${opt:region, self:custom.defaultRegion}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'secretsmanager:GetSecretValue'
          Resource:
              - '*'

custom:
  pythonRequirements:
    usePipenv: true
  defaultStage: dev
  defaultRegion: ap-northeast-1
  environment:
    dev:
      SECRET_NAME: dev/slack
    prod:
      SECRET_NAME: prod/slack
functions:
  test:
    handler: handler.test
    environment: ${self:custom.environment.${self:provider.stage}}
  alert_slack:
    handler: slack.alert_slack
    environment: ${self:custom.environment.${self:provider.stage}}

stepFunctions: ${file(includes/state-machines.yml)}

plugins:
  - serverless-step-functions
  - serverless-python-requirements
